In [15]:
import torch
import numpy as np

1.直接创建

In [16]:
t1 = torch.tensor([1, 2, 3])  # 1D tensor
t2 = torch.tensor([[1, 2], [3, 4]])  # 2D tensor
t3 = torch.tensor([1.5, 2.0], dtype=torch.float32)  # 指定数据类型（float32）
t4 = torch.tensor((1, 2, 3), dtype=torch.int64)  # 从元组创建
print(t1,t2,t3,t4)

tensor([1, 2, 3]) tensor([[1, 2],
        [3, 4]]) tensor([1.5000, 2.0000]) tensor([1, 2, 3])


2.从np数组创建

In [17]:
np_arr = np.array([[1, 2], [3, 4]], dtype=np.float32)
t = torch.from_numpy(np_arr)
print(t)

tensor([[1., 2.],
        [3., 4.]])


3.创建指定形状的未初始化

In [35]:
t = torch.empty((2, 3))  # 2行3列的未初始化tensor
print(t)
t = torch.empty(1, 2, 3, dtype=torch.int32)  # 3D tensor，指定dtype
print(t)
t=torch.Tensor(2,3)
print(t)

tensor([[1.3421e+05, 9.2346e-43, 2.8026e-45],
        [0.0000e+00, 4.2039e-45, 0.0000e+00]])
tensor([[[         0, 1072693248,          0],
         [1073741824,          0, 1074266112]]], dtype=torch.int32)
tensor([[1.3421e+05, 9.2346e-43, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])


4.创建全0或者全1

In [19]:
t=torch.zeros(3,4)
print(t)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


5.创建序列

In [20]:
t = torch.arange(5)
print(t)
t = torch.arange(1, 10, 2)
print(t)

tensor([0, 1, 2, 3, 4])
tensor([1, 3, 5, 7, 9])


In [21]:
t = torch.linspace(0, 1, 5)
print(t)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [24]:
t = torch.logspace(0, 6, 3,base=2)
print(t)

tensor([ 1.,  8., 64.])


6.随机初始化tensor

In [28]:
t = torch.rand(2, 3)  # 2x3 矩阵，元素在[0,1)随机
print(t)
t = torch.randint(1, 10, (3,2))  # [1,10) 随机整数，形状(3,2)
print(t)
t = torch.randn(2, 2)  # 2x2 矩阵，元素服从N(0,1)
print(t)
t = torch.normal(mean=torch.tensor([0.0, 1.0]), std=torch.tensor([0.1, 0.2]))
print(t)
t = torch.randperm(5)  # 例如 [3, 0, 2, 4, 1] 随机采样
print(t)

tensor([[0.3354, 0.5940, 0.3592],
        [0.6591, 0.1147, 0.0453]])
tensor([[4, 6],
        [2, 6],
        [1, 5]])
tensor([[ 0.1685,  1.4157],
        [-0.5498, -1.3218]])
tensor([-0.0586,  1.2571])
tensor([3, 0, 4, 2, 1])


7.特殊矩阵

In [29]:
t = torch.eye(3)  # 3x3 单位矩阵（对角线为1，其余为0）
print(t)
t = torch.eye(2, 3)  # 2x3 矩阵，对角线为1
print(t)
t = torch.diag(torch.tensor([1, 2, 3]))  # 3x3 对角矩阵，对角线为1,2,3
print(t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.]])
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


8.根据已有tensor创建

In [33]:
t = torch.Tensor([[1, 2], [3, 4]])
t_zero = torch.zeros_like(t)  # 2x2 全零矩阵，dtype与t一致
t_one=torch.ones_like(t)
t_rand=torch.rand_like(t)
print(t)
print(t_zero)
print(t_one)
print(t_rand)

tensor([[1., 2.],
        [3., 4.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3705, 0.9949],
        [0.6342, 0.3004]])
