In [16]:
from tempfile import tempdir

import torch
import numpy as np

1.张量元素类型转化

In [17]:
tensor1=torch.tensor([1,2,3])
print(tensor1.dtype)

torch.int64


In [18]:
tensor1=tensor1.type(torch.float)
print(tensor1.dtype)

torch.float32


In [19]:
tensor1=tensor1.half()
print(tensor1.dtype)

torch.float16


In [20]:
tensor1=tensor1.to(torch.complex64)
print(tensor1.dtype)
print(tensor1)

torch.complex64
tensor([1.+0.j, 2.+0.j, 3.+0.j])


2.tensor与nd.array相互转化
---
1.tensor-->ndarray

In [21]:
tensor1=torch.rand(3,2)
np.set_printoptions(precision=4)
print(tensor1)

tensor([[0.8459, 0.4668],
        [0.6050, 0.3877],
        [0.1084, 0.1121]])


In [26]:
ndarray1=tensor1.numpy()
print(ndarray1)

[[0.8459 0.4668]
 [0.605  1.    ]
 [0.1084 0.1121]]
tensor([[0.8459, 0.4668],
        [0.6050, 1.0000],
        [0.1084, 0.1121]])
[[0.8459 0.4668]
 [0.605  1.    ]
 [0.1084 0.1121]]


In [27]:
tensor1[1][1]=1.0
print(tensor1)
print(ndarray1)

tensor([[0.8459, 0.4668],
        [0.6050, 1.0000],
        [0.1084, 0.1121]])
[[0.8459 0.4668]
 [0.605  1.    ]
 [0.1084 0.1121]]


发现会共享同一份内存 使用copy来避免

In [29]:
ndarray2=tensor1.numpy().copy()
print(ndarray2)
tensor1[1][1]=2.1212
print(tensor1)
print(ndarray2)

[[0.8459 0.4668]
 [0.605  1.    ]
 [0.1084 0.1121]]
tensor([[0.8459, 0.4668],
        [0.6050, 2.1212],
        [0.1084, 0.1121]])
[[0.8459 0.4668]
 [0.605  1.    ]
 [0.1084 0.1121]]


2.ndarray-->torch 也是共享内存

In [30]:
ndarray1=np.random.randn(3,2)
tensor1=torch.from_numpy(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[-0.2326, -0.5278],
        [-1.1086,  0.2177],
        [-1.3938, -0.7473]], dtype=torch.float64)
[[-0.2326 -0.5278]
 [-1.1086  0.2177]
 [-1.3938 -0.7473]]


In [33]:
tensor2=torch.from_numpy(ndarray2.copy())
tensor2[:,1]=tensor2[:,1]*2
print(tensor2)
print(ndarray2)

tensor([[0.8459, 0.9336],
        [0.6050, 2.0000],
        [0.1084, 0.2242]])
[[0.8459 0.4668]
 [0.605  1.    ]
 [0.1084 0.1121]]


3.使用tensor方法直接转化为Tensor 参考01方式8

4.张量与标量的转化 标量长度只能为1

In [35]:
tensor1=torch.tensor(10)#torch.tensor([10])等价
print(tensor1)
print(tensor1.item())

tensor(10)
10
