In [12]:
import torch

In [13]:
x=torch.tensor(10.0)
y=torch.Tensor([3])
print(x)
print(y)

tensor(10.)
tensor([3.])


In [14]:
#初始化参数
w=torch.rand(1,1,requires_grad=True)
b=torch.rand(1,1,requires_grad=True)


In [15]:
#前向传播 得到输出结果
z=w*x+b
print(z)

tensor([[4.8104]], grad_fn=<AddBackward0>)


In [16]:
print(x.is_leaf)
print(w.is_leaf)
print(y.is_leaf)
print(b.is_leaf)
print(z.is_leaf)

True
True
True
True
False


In [19]:
#设置损失函数
loss=torch.nn.MSELoss()
loss_value=loss(z,y)
print(loss_value)
print(loss_value.is_leaf)

tensor(3.2775, grad_fn=<MseLossBackward0>)
False


In [20]:
#方向传播
loss_value.backward()

In [21]:
#查看梯度
print(w.grad)
print(b.grad)

tensor([[36.2075]])
tensor([[3.6207]])
