In [1]:
import torch

In [2]:
x=torch.tensor(2.0,requires_grad=True)
y=x.detach()
print(x,x.requires_grad,id(x))
print(y,y.requires_grad,id(y))

tensor(2., requires_grad=True) True 2581680716352
tensor(2.) False 2581680714752


In [3]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

5915076001920
5915076001920


共享内存

In [22]:
# print(x)
# y.zero_()
# print(x)

In [4]:
z1=x**2
z2=y**2
print(z1)
print(z2)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [5]:
z1.sum().backward()

In [6]:
# z2.sum().backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [8]:
x=torch.ones((2,2),requires_grad=True)
y=x*x
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [9]:
,#分离y
u=y.detach()
print(u)

tensor([[1., 1.],
        [1., 1.]])


u已经分离 相当于常数

In [10]:
#让u参与新张量的计算
z=u*x
print(z)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [12]:
z.sum().backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [13]:
print(x.grad==u)

tensor([[True, True],
        [True, True]])
