In [37]:
import torch

用两组数据对比 detach和data的区别

In [38]:
x1 = torch.tensor([1.0, 2, 3], requires_grad=True)
x2 = torch.tensor([1.0, 2, 3], requires_grad=True)
print(x1)
print(x2)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [39]:
y1=x1.sigmoid()
y2=x2.sigmoid()
print(y1)
print(y2)

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)


In [40]:
# y1.sum().backward()
# y2.sum().backward()
# print(x1.grad)
# print(x2.grad)

data vs detach
---
data修改不会被微分引擎跟踪 最好是只读 脱离了计算图
detach保证脱离后 不再进行反向传播 安全脱离计算图

In [41]:
z1=y1.data
z2=y2.detach()
print(z1)
print(z2)

tensor([0.7311, 0.8808, 0.9526])
tensor([0.7311, 0.8808, 0.9526])


In [42]:
z1.zero_()
z2.zero_()
print(y1)
print(y2)

tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)
tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)


In [43]:
y1.sum().backward()
print(x1.grad)

tensor([0., 0., 0.])


已经脱离了计算图 不能进行反向传播

In [44]:
# y2.sum().backward()
# print(x2.grad)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [3]], which is output 0 of SigmoidBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).