In [1]:
import torch
import torch.nn as nn

1.目标值为顺序编码的标签

In [2]:
input=torch.randn(6,8)
print(input)
#pred=torch.softmax(input,dim=1) 可以不转化 底层会自动处理

tensor([[-0.8199, -2.2862,  0.8691,  0.4446, -0.4415, -0.9398,  1.1690,  0.2205],
        [-0.3119, -0.2677, -1.9701, -0.5646,  2.0053, -2.8736, -0.6988,  2.0803],
        [ 0.5311,  1.9193,  0.5988,  1.9165,  1.4562,  0.9338,  0.1469, -0.6808],
        [ 1.7323,  2.2358, -0.5058, -1.6640,  0.2147,  0.7957, -0.1470,  0.9513],
        [-0.3497,  0.3672,  0.0603,  0.3168, -0.4400, -0.0285, -0.0079,  0.2949],
        [-0.1036, -0.9294, -1.7420, -0.7372,  1.2914, -0.9666, -1.0091, -0.6907]])


In [4]:
#目标值
target=torch.tensor([1,0,3,7,5,2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [7]:
#定义损失函数
loss=nn.CrossEntropyLoss()
output=loss(input,target)
print(output)

tensor(2.8559)


2.目标值为独热编码

In [8]:
input=torch.randn(6,8)
print(input)
target=torch.randn(6,8).softmax(dim=1)
print(target)

tensor([[ 0.7671, -0.0553,  0.9249, -1.8558,  0.4192,  1.6342,  0.8465, -1.0076],
        [ 0.0428, -1.1538, -0.5795, -0.1359, -1.2409,  0.3684,  0.7904, -0.8924],
        [-0.4194, -1.7978, -1.3451,  0.3134,  0.5321, -0.3091, -0.2907, -0.2037],
        [ 0.7914,  0.9482,  1.3269, -0.4258,  0.8379,  1.6942,  0.5029,  1.0110],
        [-0.6524, -0.1773, -0.2832, -1.0151,  1.4967,  0.3100,  0.8176, -1.8125],
        [-1.2103, -0.5994, -0.3338,  0.2103, -1.3858, -0.8055, -1.0894,  1.8843]])
tensor([[0.1997, 0.1326, 0.1217, 0.3679, 0.0536, 0.0500, 0.0361, 0.0383],
        [0.0720, 0.1813, 0.4540, 0.0333, 0.0437, 0.0429, 0.1077, 0.0652],
        [0.1846, 0.0452, 0.0484, 0.0837, 0.1951, 0.0734, 0.0174, 0.3522],
        [0.1084, 0.0266, 0.2020, 0.0832, 0.0120, 0.2819, 0.0306, 0.2554],
        [0.3069, 0.1729, 0.0114, 0.0775, 0.0617, 0.0547, 0.1466, 0.1684],
        [0.1519, 0.1968, 0.0606, 0.3944, 0.0801, 0.0353, 0.0402, 0.0406]])


In [9]:
loss=nn.CrossEntropyLoss()
output=loss(input,target)
print(output)

tensor(2.4935)
